"""Initial

Revision ID: 25c27798420b
Revises:
Create Date: 2026-03-17 13:09:02.188133

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "25c27798420b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cryptocurrencies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("circulating_supply", sa.Float(), nullable=True),
        sa.Column("usd_price", sa.Float(), nullable=True),
        sa.Column("usd_market_cap", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cryptocurrencies_slug"), "cryptocurrencies", ["slug"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cryptocurrencies_slug"), table_name="cryptocurrencies")
    op.drop_table("cryptocurrencies")
    # ### end Alembic commands ###
